task(add-basejump-announcement): Add alert and modal for Base migration
gnars-dao/gnars-frontend pull request #17
Opened 2024-04-05 01:17 UTC by asmattic

Add alert and modal for Base migration

https://github.com/gnars-dao/gnars-frontend/issues/16#issue-2209616676

2024-04-05 16:31 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +                  In the meantime, auctions and governance on Base are live <TextLink rel="noopener noreferrer" isExternal href="https://nouns.build/dao/base/0x880fb3cf5c6cc2d7dfc13a993e839a9411200c1
Would be good to move the link to a variable at the top of the file and just pass it in to the renderers since it's used 3 times.

2024-04-05 16:32 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +// @ts-ignore
what is this hidding? 👀

2024-04-05 16:41 UTC, mulfdev requested changes
Build is failing. Let's ensure we have a working build before submitting the pr

2024-04-05 16:53 UTC, bagelface commented
Depending on the amount of work, would like to see the banner (not the modal) applied to any page on the site. For example:

https://www.gnars.wtf/dao
https://www.gnars.wtf/claim
https://www.gnars.wtf/playground
http://localhost:3000/gnar/5017
http://localhost:3000/gnar/1
http://localhost:3000/gnar/5018

But, tbh would also like to prioritize getting this out sooner than later. So if it's going to take more than a day I'd say let's just ship it as is.

2024-04-05 16:59 UTC, bagelface commented
I'd also like to suggest changing the banner text to a reduced version of the modal. So instead:

title: `Gnars have BASE JUMPED`
body: `We're currently updating this site to be fully operation on Base. Stay tuned ⌐◨-◨\m/`

2024-04-05 17:06 UTC, bagelface requested changes
see comments

2024-04-05 19:45 UTC, asmattic commented
> Depending on the amount of work, would like to see the banner (not the modal) applied to any page on the site. For example:
> 
> https://www.gnars.wtf/dao (http://www.localhost:3000/dao) https://www.gnars.wtf/claim (http://www.localhost:3000/claim) https://www.gnars.wtf/playground (http://www.localhost:3000/playground) https://www.gnars.wtf/gnar/5017 (http://www.localhost:3000/gnar/5017) https://www.gnars.wtf/gnar/1 (http://www.localhost:3000/gnar/1) https://www.gnars.wtf/gnar/5018 (http://www.localhost:3000/gnar/5018)
> 
> But, tbh would also like to prioritize getting this out sooner than later. So if it's going to take more than a day I'd say let's just ship it as is.

Resolved, moved the alert to `_app.tsx` from `index.tsx`.

2024-04-05 20:22 UTC, asmattic commented
> Let's ensure we have a working build and resolve the comments as well. Thanks

<img width="587" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/cdff1055-f16c-4f89-ac53-a5046e5b1b41">

To view the build log, I'll need read permissions or a way to interact with the build jobs. Is there a recommended path here?

2024-04-05 22:50 UTC, mulfdev commented
> > Let's ensure we have a working build and resolve the comments as well. Thanks
> 
> 
> 
> <img width="300" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/cdff1055-f16c-4f89-ac53-a5046e5b1b41">
> 
> 
> 
> To view the build log, I'll need read permissions or a way to interact with the build jobs. Is there a recommended path here?

The errors in question are not Vercel specific so you do not require any additional permissions 

![image](https://github.com/gnars-dao/gnars-frontend/assets/63870279/abc7381b-b6a2-454f-a962-8722f418aff9)

Running a build locally will ensure these errors are resolved before submission. Thank you

2024-04-05 23:28 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +}
needs EOL

2024-04-05 23:28 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +        <ModalHeader textAlign={"center"} textStyle={"h2"}>Gnars have BASE Jumped!</ModalHeader>
`Gnars have BASE JUMPED!`

2024-04-05 23:28 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +        <AlertTitle textAlign={'center'} textStyle={"h2"} py={2}>Gnars have BASE Jumped!</AlertTitle>
`Gnars have BASE JUMPED!`

2024-04-05 23:32 UTC, asmattic commented
Thanks, I'll make sure to build locally and any warns are removed in the future. 

For the `UpdateDelegateModal.tsx` component (below) the last commit 5 months ago was removing a dependency, and the one causing the warn appears to be more mission critical. The alert and modal are ready, but I would need either time to test or local knowledge for the `UpdatedelegateModal.tsx` component.

<img width="700" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/aed16e33-a9ed-47f0-95bd-511240b1a729">

2024-04-05 23:41 UTC, mulfdev commented
The **errors** are the issue. The unescaped characters. Not the warnings

2024-04-05 23:54 UTC, asmattic commented
> The **errors** are the issue. The unescaped characters. Not the warnings

I'm not getting that locally. Is it the `&apos;`?

2024-04-06 00:39 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +            We &#39; re currently updating this site to be fully operation on Base. Stay tuned. ⌐◨-◨\m/
spaces around this create this
<img width="85" alt="Screenshot 2024-04-05 at 8 36 45 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/87501783/bb0b3ebc-7922-4be1-aa43-e1001ff82292">

2024-04-06 00:39 UTC, bagelface commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +                We &#39; re currently updating this site to be fully operational on Base. In the meantime, auctions and governance are live on Base <TextLink href={baseLink}>here</TextLink>.
spaces around this create
<img width="85" alt="Screenshot 2024-04-05 at 8 36 45 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/87501783/86ce22a9-5f96-4405-89dc-b0554d86371c">

2024-04-06 00:45 UTC, mulfdev requested changes

2024-04-06 00:45 UTC, mulfdev commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +  const { } = useDisclosure({ defaultIsOpen: true })
if you arent using the values, no need for the braces

2024-04-06 00:45 UTC, bagelface approved these changes
lgtm

2024-04-06 23:26 UTC, mulfdev requested changes

2024-04-06 23:26 UTC, mulfdev commented on packages/webapp/components/BaseJumpAnnouncement.tsx
> +  const { } = useDisclosure({ defaultIsOpen: true })
lets get the empty braces  removed and we can merge it.

2024-04-06 23:28 UTC, mulfdev approved these changes

2024-04-06 23:32 UTC, merged