Update webapp treasury viewer to show Base treasury and multi-sig balances
gnars-dao/gnars-frontend pull request #24
Opened 2024-04-13 22:47 UTC by r4topunk

I have updated it in 2 parts, the first one using the useBalance hooks, e the second one creating a new functions to get a list of token balances from a wallet.

I don't know if I liked the code I wrote, but I'm available to update the code with some tips.

I have added Base to Wagmi config, but maintain Mainnet while we are in the migration.

And another thing I think I'm not right, is the update in the sdk file, I just updated the file directly, but I think this file is generated and this is not the right approach.

Anyway, like I said, I'm willing to change the code and try again.

This code resolves the #21 issue

<img width="268" alt="Captura de Tela 2024-04-13 às 19 47 07" src="https://github.com/gnars-dao/gnars-frontend/assets/43586732/a390cb49-359d-4b39-a00e-18a7527bec19">

2024-04-16 15:47 UTC, bagelface commented on packages/webapp/constants/gnarsDao.ts
> +export const BASE_TREASURY_ADDRESS = "0x72ad986ebac0246d2b3c565ab2a1ce3a14ce6f88"
would recommend using the checksum version of all of these addresses

2024-04-16 15:49 UTC, bagelface commented on packages/webapp/utils/sdk.ts
> + * [__View Contract on Ethereum BaseScan__](https://basescan.org/address/0x880Fb3Cf5c6Cc2d7DFC13a993E839a9411200C17)
Was all this manually updated or was it generated using `yarn wagmi generate`?

2024-04-16 15:50 UTC, bagelface commented on packages/webapp/utils/web3.ts
> +}
line break at the end of this file

2024-04-16 15:52 UTC, bagelface commented on packages/webapp/utils/web3.ts
> +export function getTokensValues(holder: `0x${string}`, tokens: `0x${string}`[]) {
not sure what the convention is throughout this project, but always nice to include the return type

2024-04-16 15:57 UTC, bagelface approved these changes
Everything here looks solid to me. Code is nice and clean and everything works as expected. Dropped a few small notes but, none of them would block this from being merge imo.

2024-04-16 19:44 UTC, r4topunk commented
@bagelface I will update the code with your considerations, then I will ask for another review then I will ask for merge

2024-04-17 00:53 UTC, mulfdev requested changes
Per out tech pod meeting today, lets integrate the token formatting and wallet/chain agnostic data fetching. great work!

2024-04-26 00:36 UTC, sktbrd commented
Looks good to me. @bagelface @mulfdev what you think ?

2024-04-27 00:38 UTC, merged