Update non wagmi webapp packages to major versions
gnars-dao/gnars-frontend pull request #29
Opened 2024-04-22 00:30 UTC by asmattic

2024-04-22 00:38 UTC, asmattic commented
All non `wagmi` related packages updated to next major versions.

2024-04-22 00:49 UTC, asmattic commented
Not sure exactly where the hardhat error is originating, if it just needs the `.env` keys in Vercel but the `webapp` builds without errors locally. 

<img width="500" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/0eea5758-9309-4f7a-8781-d0dc6d043ec4">

2024-04-22 17:46 UTC, asmattic commented
<img width="1000" alt="Screenshot 2024-04-22 at 1 16 15 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/3783604a-11f6-487f-ac5e-2c654851448d">

2024-04-22 19:26 UTC, mulfdev commented
yeah no worries, as long as web builds we're good. will review today

2024-04-24 21:21 UTC, asmattic commented
All added formatting unrelated to PR removed. Local webapp build confirmed still working.

<img width="1200" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/e2573cd2-bd86-4df4-b37e-ded7ebdd871e">

2024-04-24 22:17 UTC, mulfdev commented on .npmrc
lets remove this

2024-04-24 22:17 UTC, mulfdev commented on .nvmrc
per our convo, lets only specify major version

2024-04-24 22:18 UTC, mulfdev commented on package.json
only major version of node should be specified

2024-04-24 22:18 UTC, mulfdev commented on packages/webapp/.npmrc
remove this file

2024-04-24 22:18 UTC, mulfdev commented on packages/webapp/data/image-data-V2.json
why is this here?

2024-04-24 22:59 UTC, asmattic commented
Removed `.npmrc` files. Kept `node@v18.20.2`. Webapp builds.

<img width="1308" alt="image" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/098c1ca5-0496-42a1-9d2a-5b5731488201">

2024-04-25 13:52 UTC, asmattic reviewed
Addressed all requested changes

2024-04-25 13:52 UTC, asmattic commented on .nvmrc
Specified node 18 major version only

2024-04-27 00:32 UTC, mulfdev commented
the build for webapp does not work presently
![CleanShot 2024-04-26 at 19 32 22](https://github.com/gnars-dao/gnars-frontend/assets/63870279/328e40b1-f197-4b2d-99ca-2f1427bb0a3e)

2024-04-27 00:33 UTC, mulfdev requested changes
![CleanShot 2024-04-26 at 19 32 54](https://github.com/gnars-dao/gnars-frontend/assets/63870279/711d48ad-e5d8-42f0-a20a-c1e57a4209b9)

2024-04-27 18:08 UTC, mulfdev commented
Also let's rebase off the most recent merge

2024-04-29 15:44 UTC, asmattic commented
> ![CleanShot 2024-04-26 at 19 32 54](https://private-user-images.githubusercontent.com/63870279/326138469-711d48ad-e5d8-42f0-a20a-c1e57a4209b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDUyMDIsIm5iZiI6MTcxNDQwNDkwMiwicGF0aCI6Ii82Mzg3MDI3OS8zMjYxMzg0NjktNzExZDQ4YWQtZTVkOC00MmYwLWEyMGEtYzFlNTdhNDIwOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE1MzUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YmRjMjRhMWE1NjNiZWFkZjAzYTMzYjRjYjY4NTc3NjMwMGYxNmJjM2Q4MTRjMDIzMTgwYzkyMTMxOTE2NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zrBUlr576hLC_J902oH-2TOB5IbWvhqmsWCj_KwTehI)

Hmm, I was getting this error before but it seemed to be only related to upgrading `wagmi` or `viem` versions. I'll rebase and get try to get my `pnpm` environment clean so I can replicate and fix. From what I saw of the recent merge, the chain config in there likely nullifies this issue. I'll push those changes with any additional comments or considerations today.

2024-04-29 17:22 UTC, mulfdev commented
Vercel preview is only for the given branch. Didnt see the branch change, let's limit that in the future or close and reopen the pr.

2024-04-29 19:27 UTC, asmattic commented
> Vercel preview is only for the given branch. Didnt see the branch change, let's limit that in the future or close and open a new pr.

I'll make sure to have `main` as the comparison fork branch for future PR's. In the interest of not creating a 3rd PR for this issue I think we should wrap up this issue here. 

I just need whatever is causing the `webapp` build error being produced in the Vercel preview build to debug.

2024-04-29 21:40 UTC, mulfdev commented
> > Vercel preview is only for the given branch. Didnt see the branch change, let's limit that in the future or close and open a new pr.
> 
> I'll make sure to have `main` as the comparison fork branch for future PR's. In the interest of not creating a 3rd PR for this issue I think we should wrap up this issue here.
> 
> I just need preview build logs to locate and debug the cause of the `webapp` build error produced.

![CleanShot 2024-04-29 at 16 40 09](https://github.com/gnars-dao/gnars-frontend/assets/63870279/747adc50-0a03-4f0b-9452-362847cd48ee)

2024-04-29 21:45 UTC, mulfdev commented
for commit hash [ae732f9](https://github.com/asmattic/gnars-frontend/commit/ae732f9f0a5717cb37f638604db1570dab09a7f3)

![CleanShot 2024-04-29 at 16 45 03](https://github.com/gnars-dao/gnars-frontend/assets/63870279/6d16df5e-777d-47c9-bfa7-d4e8318f238a)


the vercel logs dont reveal anything here that wasnt determinable on local?

2024-04-29 21:47 UTC, mulfdev requested changes
![326596999-6d16df5e-777d-47c9-bfa7-d4e8318f238a](https://github.com/gnars-dao/gnars-frontend/assets/63870279/2b8fab14-ec70-4beb-aed7-36224c25bf5a)

2024-04-29 22:10 UTC, asmattic commented
> ae732f9

Thanks, I'll debug from there and try and replicate locally. I'll request re-review when I have tracked down the root cause.

2024-05-01 18:20 UTC, asmattic commented
Dependency `connectkit@^1.5.1` was pulling in `connectkit@1.7.x` (see breaking changes here)[https://docs.family.co/connectkit/migration-guide#section-170-breaking-changes-update-packages] which requires `wagmi@v2`. The `alchemyId` error was an artifact of the `wagmi@v2` larger upgrade due to the `connectkit` relation.  

Replicated the `alchemyId` type error removing `pnpm-lock.yaml` in root and running `pnpm install` and `build` in `webapp` below where you can see the `connectkit` breaking version.

<img width="1003" alt="connectkit-1 7 x depends on wagmiv2- 2024-05-01 at 2 00 00 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/20761346/67064124-2a79-43ae-b2fa-3a7b5b3fcb90">

Fixing `connectkit` to `v1.5.1` resolves this issue and runs a successful build. I'll post another local build screenshot, lol. 

I'm pretty confident if another build error occurs, it'll at least be a new one.

2024-05-01 18:29 UTC, mulfdev commented
![CleanShot 2024-05-01 at 13 29 02](https://github.com/gnars-dao/gnars-frontend/assets/63870279/e53b5062-5d71-4800-a1b4-dd35bf7603cb)
🔥

2024-05-01 18:39 UTC, merged